-- liquibase formatted sql

-- changeset csa21472001:create-ad_entity-table
CREATE TABLE ad
(
--id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pk                 serial PRIMARY KEY,
    price               integer,
    title               text,
    description         text,
    user_entity_id      int4,
    image_entity_id     int4
);