-- liquibase formatted sql

-- changeset Maria:1
CREATE TABLE comment
(
comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
authors_id NOT NULL,
authors_image,
first_name NOT NULL,
comment_time TIMESTAMP WITHOUT TIMEZONE NOT NULL,
text TEXT,
ad_id NOT NULL,
PRIMARY KEY (authors_id)
);