-- liquibase formatted sql

<<<<<<< HEAD
-- changeset csa21472001:create-comment_entity-table
CREATE TABLE comment_entity
(
    id                       serial PRIMARY KEY,
    price                    integer,
    created_at               interval,
    text                     text,
    user_entity_id bigint REFERENCES user_entity (id),
    ad_id bigint REFERENCES ad_entity (id),
=======
-- changeset Maria:1
CREATE TABLE comment
(
comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
authors_id NOT NULL,
authors_image,
first_name NOT NULL,
comment_time TIMESTAMP WITHOUT TIMEZONE NOT NULL,
text TEXT,
ad_id NOT NULL,
PRIMARY KEY (authors_id)
>>>>>>> 9307f98 (для Влада)
);