-- liquibase formatted sql

-- changeset Maria:1
CREATE TABLE comment
(
comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
authors_id INT NOT NULL,
authors_image VARCHAR,
first_name VARCHAR NOT NULL,
comment_time INT NOT NULL,
text TEXT,
--ad_id NOT NULL,
PRIMARY KEY (authors_id)
);