CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    phone      VARCHAR(255),
    email      VARCHAR(255),
    image      VARCHAR(255),
    role       VARCHAR(255),
    username   VARCHAR(255),
    password   INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE ads
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image       VARCHAR(255),
    title       VARCHAR(255),
    price       INTEGER,
    description VARCHAR(255),
    author_id   INTEGER,
    CONSTRAINT pk_ads PRIMARY KEY (id)
);

ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);


CREATE TABLE comments
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    author_id  INTEGER,
    ad_id INTEGER,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_COMMENT FOREIGN KEY (ad_id) REFERENCES ads (id);