-- liquibase formatted sql

-- changeset krassotin:1
create table ads (
    id int4 generated by default as identity,
    email varchar(255),
    first_name varchar(255),
    image varchar(255),
    last_name varchar(255),
    phone varchar(255)
    role int4,
    primary key (id))