-- liquibase formatted sql

-- changeset andryDO2009:1
CREATE TABLE ads (
    id INTEGER generated by default as identity PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    title VARCHAR(32) NOT NULL,
    image_path VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT price_constraint CHECK (price > 0 AND price < 10000000),
    FOREIGN KEY(user_id) REFERENCES users(id)
);
