-- liquibase formatted sql

-- changeset andryDO2009:1
CREATE TABLE comments (
    id INTEGER generated by default as identity PRIMARY KEY,
    text VARCHAR(64) NOT NULL,
    created_at BIGINT NOT NULL,
    user_id INTEGER,
    ad_id INTEGER,
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(ad_id) REFERENCES ads(id)
);
