-- liquibase formatted sql

-- changeset yuzu:1

create table comments (
id int8 generated by default as identity,
created_at timestamp not null,
text varchar(255) not null,
ad_id int8,
author_id int8,
primary key (id))