-- liquibase formatted sql

-- changeset syutins:1
CREATE TABLE comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   author_id BIGINT,
   ad_id INTEGER,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   text VARCHAR(255),
   CONSTRAINT pk_comments PRIMARY KEY (id)
);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AD FOREIGN KEY (ad_id) REFERENCES ads (id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);