-- liquibase formatted sql

-- changeset syutins:1
CREATE TABLE images (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        file_size BIGINT,
                        media_type VARCHAR(255),
                        file_path VARCHAR(255),
                        data OID,
                        CONSTRAINT pk_images PRIMARY KEY (id)
);

-- changeset syutins:4
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       first_name VARCHAR(255) NOT NULL,
                       last_name VARCHAR(255) NOT NULL,
                       phone VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL,
                       image_id INTEGER,
                       CONSTRAINT pk_users PRIMARY KEY (id)
);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uc_users_image UNIQUE (image_id);
ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id);

-- changeset syutins:2
CREATE TABLE ads (
                     id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                     author_id BIGINT NOT NULL,
                     image_id INTEGER,
                     price INTEGER NOT NULL,
                     title VARCHAR(100) NOT NULL,
                     description VARCHAR(255) NOT NULL,
                     CONSTRAINT pk_ads PRIMARY KEY (id)
);
ALTER TABLE ads ADD CONSTRAINT uc_ads_image UNIQUE (image_id);
ALTER TABLE ads ADD CONSTRAINT FK_ADS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);
ALTER TABLE ads ADD CONSTRAINT FK_ADS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id);


-- changeset syutins:5
CREATE TABLE comments (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          author_id BIGINT,
                          ad_id INTEGER,
                          created_at TIMESTAMP WITHOUT TIME ZONE,
                          text VARCHAR(255),
                          CONSTRAINT pk_comments PRIMARY KEY (id)
);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AD FOREIGN KEY (ad_id) REFERENCES ads (id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);
