-- liquibase formatted sql

-- changeset syutins:1
CREATE TABLE comments (
  pk INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   author_id INTEGER,
   image_id INTEGER,
   ad_id INTEGER,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   text VARCHAR(255),
   CONSTRAINT pk_comments PRIMARY KEY (pk)
);
ALTER TABLE comments ADD CONSTRAINT uc_comments_image UNIQUE (image_id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AD FOREIGN KEY (ad_id) REFERENCES ads (id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id);