-- liquibase formatted sql

-- changeset syutins:1
CREATE TABLE ads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   author_id BIGINT NOT NULL,
   image_id INTEGER,
   price INTEGER NOT NULL,
   title VARCHAR(100) NOT NULL,
   description VARCHAR(255) NOT NULL,
   CONSTRAINT pk_ads PRIMARY KEY (id)
);
ALTER TABLE ads ADD CONSTRAINT uc_ads_image UNIQUE (image_id);
ALTER TABLE ads ADD CONSTRAINT FK_ADS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);
ALTER TABLE ads ADD CONSTRAINT FK_ADS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id);