-- liquibase formatted sql

-- changeset syutins:1
CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   phone VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL,
   image_id INTEGER,
   CONSTRAINT pk_users PRIMARY KEY (id)
);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uc_users_image UNIQUE (image_id);
ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id);