--liquibase formatted sql
--changeset Arihin


CREATE TABLE image
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image oid,
    CONSTRAINT image_pkey PRIMARY KEY (id)
    );


CREATE TABLE user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    phone varchar(255),
    role varchar(255),
    username varchar(255),
    user_image bigint,
    CONSTRAINT users_pkey PRIMARY KEY (id)

    CONSTRAINT user_image_fkey FOREIGN KEY (user_image)
        REFERENCES public.image (user_image) MATCH SIMPLE
    );

CREATE TABLE ad
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description varchar(255),
    price int,
    title varchar(255),
    ad_image bigint,
    user_id bigint NOT NULL,
    CONSTRAINT ad_pkey PRIMARY KEY (id),
    CONSTRAINT ad_image_fkey FOREIGN KEY (ad_image)
    REFERENCES public.image (id) MATCH SIMPLE
    CONSTRAINT user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_entity (id) MATCH SIMPLE
    );


CREATE TABLE comment
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at bigint,
    text varchar(255),
    ad_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT comment_pkey PRIMARY KEY (id),
    CONSTRAINT ad_id_fkey FOREIGN KEY (ad_id)
    REFERENCES public.ad (id) MATCH SIMPLE
    CONSTRAINT user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_entity (id) MATCH SIMPLE

    );






