-- liquibase formatted sql

-- changeset 1
create table if not exists users
(
    id         integer generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255),
    image      varchar(255),
    username   varchar(255) unique not null,
    phone      varchar(255),
    role       varchar(255) not null
);
create table if not exists ad(
    pk integer generated by default as identity primary key,
    image varchar(255),
    price integer,
    title varchar(255),
    user_id integer references user(id) on delete cascade
);
create table if not exists comment(
    pk integer generated by default as identity primary key,
    user_first_name varchar(255),
    user_image varchar(255),
    created_at integer,
    text varchar(255),
    author_id integer references author(id) on delete cascade,
    ad_pk integer references ad(pk) on delete cascade
);
-- changeset 2
create table authorities (
    id         integer generated by default as identity primary key,
    username varchar(50) not null,
    authority varchar(50) not null,
    user_id integer references users(id) on delete cascade

);
create unique index ix_auth_username on authorities (username,authority);

-- changeset 3
alter table ad add description varchar(255);

-- changeset 4
alter table authorities drop column user_id;
-- changeset 5
create table if not exists image(
    id varchar(255) primary key,
    image bytea
);