-- liquibase formatted sql

-- changeset tukmachev:1
create table if not exists users
(
    id         integer generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255),
    image      varchar(255),
    username   varchar(255) unique not null,
    password   varchar(255),
    phone      varchar(255),
    enabled boolean not null,
    role       varchar(255)
);
create table if not exists ad(
    pk integer generated by default as identity primary key,
    image varchar(255),
    price integer,
    title varchar(255),
    user_id integer references users(id) on delete cascade
);
create table if not exists comment(
    pk integer generated by default as identity primary key,
    user_first_name varchar(255),
    user_image varchar(255),
    created_at integer,
    text varchar(255),
    user_id integer references users(id) on delete cascade,
    ad_pk integer references ad(pk) on delete cascade
);
-- changeset tukmachev:2
create table if not exists authorities (
    id         integer generated by default as identity primary key,
    username varchar(50) not null,
    authority varchar(50) not null,
    user_id integer references users(id) on delete cascade

);
create unique index ix_auth_username on authorities (username,authority);

-- changeset tukmachev:3
alter table ad add description varchar(255);

-- changeset tukmachev:4
alter table authorities drop column user_id;
-- changeset tukmachev:5
create table if not exists image(
    id varchar(255) primary key,
    image bytea
);
-- changeset tukmachev:6
alter table comment drop column created_at;
alter table comment add created_at timestamp;