-- liquibase formatted sql

-- changeset 1
create table if not exists author
(
    id         integer generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255),
    email      varchar(255),
    image      varchar(255),
    phone      varchar(255),
    role       varchar(255) not null
);
create table if not exists ad(
    pk integer generated by default as identity primary key,
    image varchar(255),
    price integer,
    title varchar(255),
    author_id integer references author(id) on delete cascade
);
create table if not exists comment(
    pk integer generated by default as identity primary key,
    author_first_name varchar(255),
    author_image varchar(255),
    created_at integer,
    text varchar(255),
    author_id integer references author(id) on delete cascade,
    ad_pk integer references ad(pk) on delete cascade
);