--liquibase formatted sql

--changeset ShilovaNatalia:table comments

CREATE TABLE comments
(
    id         SERIAL PRIMARY KEY,
    ads_id     BIGINT,
    author_id  BIGINT,
    created_at VARCHAR(20),
    text       TEXT
);


--changeset ShilovaNatalia: table profileUser
drop table if exists profile_user;
CREATE TABLE profile_user
(
    user_profile_id SERIAL PRIMARY KEY,
    email           VARCHAR(50),
    first_name      VARCHAR(50),
    last_name       VARCHAR(50),
    phone           VARCHAR(50),
    reg_date        VARCHAR(50),
    city            VARCHAR(50),
    pass            VARCHAR(50),
    role            varchar(10),
    avatar_id       BIGINT
);

ALTER TABLE profile_user
    ADD CONSTRAINT FK_PROFILE_USER_ON_AVATAR FOREIGN KEY (avatar_id) REFERENCES avatar (id)
on delete cascade on update cascade ;
ALTER TABLE profile_user
    ADD constraint unique_email unique (email);


--changeset ShilovaNatalia: table ads
drop table if exists ads;
CREATE TABLE ads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    title       VARCHAR(255),
    price       INTEGER                                 NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_ads PRIMARY KEY (id)
);

ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_USER FOREIGN KEY (user_id) REFERENCES profile_user (user_profile_id)
        on delete cascade on update cascade ;


--changeset ShilovaNatalia:comments_add_fk and comments_add_fk_to_user
alter table comments
    add constraint fk_ads_user_profiles foreign key (author_id) references profile_user (user_profile_id)
        on delete cascade on update cascade ;
alter table comments
    add constraint fk_ads foreign key (ads_id) references ads (id)
        on delete cascade on update cascade ;

--changeset ShilovaNatalia:image_table

CREATE TABLE image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_size  BIGINT                                  NOT NULL,
    media_type VARCHAR(100),
    data       BYTEA,
    ads_id     BIGINT,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_ADS FOREIGN KEY (ads_id) REFERENCES ads (id)
        on delete cascade on update cascade ;

--changeset ShilovaNatalia:avatar_table
CREATE TABLE avatar
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_size  BIGINT                                  NOT NULL,
    media_type VARCHAR(255),
    data       BYTEA,
    CONSTRAINT pk_avatar PRIMARY KEY (id)
);

--changeset ShilovaNatalia:tables users and authorities
create table users
(
    username    varchar(50) not null primary key ,
    password    varchar(120) not null,
    enabled     boolean not null
);

create table authorities
(
    username varchar(50) not null,
    authority varchar(50) not null,
    foreign key (username) references users (username)
);