-- liquibase formatted sql

-- changeset: User2

-- Создание таблицы "users" для хранения информации о пользователях сайта
create table users
(
id INT not null primary key,-- Уникальный идентификатор пользователя
first_name TEXT, -- Имя пользователя,
last_name TEXT, -- Фамилия пользователя
phone_number TEXT, -- Номер телефона пользователя
email TEXT, -- почта пользователя
password TEXT, -- пароль пользователя
image VARCHAR,
role VARCHAR, --enum Role
);

-- Создание таблицы "ad" для хранения информации об объявлениях
CREATE TABLE ad
(
--id  BIGSERIAL PRIMARY KEY,
  --  pk BIGINT,  --generated by default as identity primary key,-- Уникальный идентификатор объявления
 --   image TEXT,--ссылка на фото пользователя
 --   price BIGINT NOT NULL,
 --   title TEXT -- текст объявления
     id   BIGSERIAL PRIMARY KEY,
     description varchar(255),
     price       INT,
     title       VARCHAR(255),
  --   image_id   bigint references image (id),
     author_id   BIGINT REFERENCES users(id),
     author BIGINT,
     image text,
     pk integer
);
-- Создание таблицы "comments" для хранения информации об комментариях
CREATE TABLE comments
(
 --   id BIGINT generated by default as identity primary key, -- Идентификатор автора комментария
  --  pk BIGINT NOT NULL, -- Идентификатор комментария
 --   createdAt BIGINT NOT NULL, --'дата и время создания комментария в миллисекундах с 00:00:00 01.01.1970'
  --  text TEXT NOT NULL,-- текст комментария
  --  FOREIGN KEY (pk) REFERENCES ad(id) -- Предполагается, что 'pk' в 'comments' является внешним ключом, ссылаясь на 'pk' в 'ad'
    id         BIGSERIAL PRIMARY KEY,
    created_at BIGINT,
    text       varchar(255),
    pk_ad      bigint references ad(id),
    author_id  bigint references users(id),
    author int,
    author_first_name text,
    author_image text,
    description text,
    pk INT,
    price int,
    title text
);
CREATE TABLE image (
    id SERIAL PRIMARY KEY,
    data oid,
    file_size BIGINT,
    media_type VARCHAR
);