-- liquibase formatted sql
-- changeset margo:1

CREATE TABLE "user_entity"
(
  "pk" int4 generated by default as identity,
  "email" varchar(32) NOT NULL,
  "first_name" varchar(16) NOT NULL,
  "last_name" varchar(16) NOT NULL,
  "phone" varchar(12) NOT NULL,
  "role" varchar(6) NOT NULL,
  "image_entity_id" int4 NULL,
  "password" varchar(60) NOT NULL,
  CONSTRAINT "user_entity_pkey" PRIMARY KEY ("pk")
);

CREATE TABLE "comment_entity"
(
  "pk" int4 generated by default as identity,
  "author_id" int4 NOT NULL,
  "ad_id" int4 NOT NULL,
  "author_first_name" varchar(16) NOT NULL,
  "created_at" timestamp NOT NULL,
  "text" varchar(64) NOT NULL,
  CONSTRAINT "comment_entity_pkey" PRIMARY KEY ("pk")
);

CREATE TABLE "ad_entity"
(
  "pk" int4 generated by default as identity,
  "author_id" int4 NOT NULL,
  "image_entity_id" int4 NOT NULL,
  "price" int4 NOT NULL,
  "title" varchar(32) NOT NULL,
  "description" varchar(64) NOT NULL,
  CONSTRAINT "ad_entity_pkey" PRIMARY KEY ("pk")
);

CREATE TABLE "image_entity"
(
    "id" int4 generated by default as identity,
    "file_path" text,
    CONSTRAINT "image_entity_pkey" PRIMARY KEY ("id")
);