-- liquibase formatted sql
-- changeset margo:1

CREATE TABLE "user_entity"
(
  "pk" bigint generated by default as identity,
  "email" varchar(255) NULL,
  "username" varchar(255) NULL,
  "first_name" varchar(255) NULL,
  "last_name" varchar(255) NULL,
  "phone" varchar(255) NULL,
  "role" bigint NULL,
  "image" varchar(255) NULL,
  "password" varchar(255) NULL,
  CONSTRAINT "user_entity_pkey" PRIMARY KEY ("pk")
);

CREATE TABLE "comment_entity"
(
  "pk" bigint generated by default as identity,
  "author_id" bigint NULL,
  "ad_id" bigint NULL,
  "author_image" varchar(255) NULL,
  "author_first_name" varchar(255) NULL,
  "created_at" bigint NULL,
  "text" varchar(255) NULL,
  CONSTRAINT "comment_entity_pkey" PRIMARY KEY ("pk")
);

CREATE TABLE "ad_entity"
(
  "pk" bigint generated by default as identity,
  "author_id" bigint NULL,
  "image" varchar(255) NULL,
  "price" bigint NULL,
  "title" varchar(255) NULL,
  "description" varchar(255) NULL,
  CONSTRAINT "ad_entity_pkey" PRIMARY KEY ("pk")
);

-- changeset margo:2
INSERT INTO user_entity(pk,email,username,first_name,last_name,phone,role,image,password)
VALUES(1,'indfkd@mail.ru', 'user@gmail.com', 'Ryan','Brown','+79853900335',0,NULL,'password')