-- liquibase formatted sql

-- changeset andryDO2009:1
CREATE TABLE users (
    id INTEGER generated by default as identity PRIMARY KEY,
    email_user VARCHAR(32) NOT NULL unique,
    password_user VARCHAR(255) NOT NULL,
    first_name VARCHAR(16) NOT NULL,
    last_name VARCHAR(16) NOT NULL,
    phone_user VARCHAR(16) NOT NULL,
    image_path VARCHAR(255),
    role VARCHAR(16) NOT NULL,
    CONSTRAINT phone_user_constraint CHECK (phone_user LIKE ('+7%'))
);

INSERT INTO users (email_user, password_user, first_name, last_name, phone_user, role)
VALUES ('admin@gmail.com', '$2a$12$lV7lTQdu3Elm7m3bdAAxWOs3GjvMSIYUYE7gGMqO/KF2NLakrCWdu', 'Admin', 'Adminov', '+77777777777', 'ADMIN');