-- liquibase formatted sql

-- changeset syutins:1
CREATE TABLE ads (
  ad_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   author_id BIGINT,
   image_id INTEGER,
   price INTEGER,
   title VARCHAR(255),
   CONSTRAINT pk_ads PRIMARY KEY (ad_id)
);
ALTER TABLE ads ADD CONSTRAINT uc_ads_image UNIQUE (image_id);
ALTER TABLE ads ADD CONSTRAINT FK_ADS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (user_id);
ALTER TABLE ads ADD CONSTRAINT FK_ADS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (image_id);

CREATE TABLE comments (
  comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   author_id BIGINT,
   image_id INTEGER,
   ad_id INTEGER NOT NULL,
   author_name VARCHAR(255),
   comment_date TIMESTAMP WITHOUT TIME ZONE,
   comment_text VARCHAR(255),
   CONSTRAINT pk_comments PRIMARY KEY (comment_id)
);
ALTER TABLE comments ADD CONSTRAINT uc_comments_image UNIQUE (image_id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AD FOREIGN KEY (ad_id) REFERENCES ads (ad_id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (user_id);
ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (image_id);

CREATE TABLE images (
  image_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   bytes OID,
   CONSTRAINT pk_images PRIMARY KEY (image_id)
);

CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255),
   password VARCHAR(255),
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   phone VARCHAR(255),
   role VARCHAR(255) NOT NULL,
   image_id INTEGER,
   CONSTRAINT pk_users PRIMARY KEY (user_id)
);
ALTER TABLE users ADD CONSTRAINT uc_users_image UNIQUE (image_id);
ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (image_id);