-- liquibase formatted sql
-- changeset Liz:1
create table users
(
    user_id serial primary key ,
    password varchar(10000) not null ,
    username varchar(255)not null unique ,
    first_name varchar(30) not null ,
    last_name varchar(30) not null ,
    phone varchar(12) not null ,
    role varchar(10) not null
);

-- changeset Liz:2
CREATE TABLE ads
(
    ad_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    price       INTEGER      NOT NULL,
    title       VARCHAR(32)  NOT NULL,
    user_id     INTEGER      NOT NULL,
    image_id    INTEGER      NOT NULL
);


-- changeset Liz:3
create table comments
(
    comment_id serial primary key ,
    user_id int not null references users(user_id) on delete cascade ,
    created_at timestamp not null ,
    comment_text text,
    ad_id int not null references ads(ad_id) on delete cascade
);
-- changeset Liz:4
create table images
(
    image_id bigserial primary key
);
