-- liquibase formatted sql
-- changeset Sergey:1
CREATE TABLE photos
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_Type TEXT    NOT NULL,
    data      BYTEA
);
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR DEFAULT 'USER',
    photo_id   BIGINT REFERENCES photos (id)
);
CREATE TABLE ads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT,
    price       INTEGER,
    title       TEXT,
    author_id   BIGINT REFERENCES users (id),
    photo_id    BIGINT REFERENCES photos (id)
);
CREATE TABLE comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    text      TEXT NOT NULL,
    author_id   BIGINT REFERENCES users (id),
    ad_id     BIGINT REFERENCES ads (id)
);