/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.skypro.homework.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewPassword
 */
public class NewPasswordTest {
    private final NewPassword model = new NewPassword();

    /**
     * Model tests for NewPassword
     */
    @Test
    public void testNewPassword() {
        // TODO: test NewPassword
    }

    /**
     * Test the property 'currentPassword'
     */
    @Test
    public void currentPasswordTest() {
        // TODO: test currentPassword
    }

    /**
     * Test the property 'newPassword'
     */
    @Test
    public void newPasswordTest() {
        // TODO: test newPassword
    }

}
